#!/bin/bash
set -e
#
#		Convert BASIC to programs
#
python3 ../basic/scripts/makeprogram.py $1/$1.bas $1/$1.prg
python3 ../basic/scripts/gfxconv.py $1/$1.png
#
#		Copy to storage and make it the autoexec.
#
cp $1/$1.prg $1/$1.spr storage
cp $1/$1.prg storage/autoexec.prg
#
#		Copy all the storage to emulator, where it will go to esp32 and javascript
#
cp storage/* ../emulator/storage
#
#		Run emulator
#
../emulator/eris