#!/bin/bash
set -e

pushd fonts
python3 font5x7.py
popd

pushd keyboard-map 
python3 keyconv.py $1
popd 

python3 ../assembler/easm.zip 

cp bin/a.out ../emulator/bin/kernel.rom 
cp bin/a.prg ../emulator/bin/kernel.prg 
cp bin/_binary.h ../emulator/bin/_kernel.h 
