#!/bin/bash
set -e

rm -f generated/token_test.inc  
rm -f ../emulator/storage/autoexec.prg 

pushd scripts 
rm -f prg/autoexec.prg 
python3 tables.py

python3 makeprogram.py source/sed.bas prg/sed
python3 makeprogram.py source/bgr.bas prg/bgr.prg
python3 makeprogram.py source/test.bas prg/autoexec.prg
python3 makeprogram.py source/test.bas prg/test.prg
python3 makeprogram.py source/sprites.bas prg/sprites.prg
python3 makeprogram.py source/spritecoll.bas prg/spritecoll.prg
python3 makeprogram.py source/tilemap.bas prg/tilemap.prg

cp prg/test.prg ../../emulator/bin 
cp prg/* ../../emulator/storage 

popd

pushd messages 
python3 msgconv.py
popd

cp ../kernel/bin/a.lbl generated/kernel.labels 

python3 ../assembler/easm.zip

cp bin/a.prg ../emulator/bin/basic.prg 
cp bin/_binary.h ../emulator/bin/_basic.h 

